// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/medigo/AdminDashboard.tsx": () => import("../components/mockups/medigo/AdminDashboard.tsx"),
  "./components/mockups/medigo/DoctorDashboard.tsx": () => import("../components/mockups/medigo/DoctorDashboard.tsx"),
  "./components/mockups/medigo/PatientBooking.tsx": () => import("../components/mockups/medigo/PatientBooking.tsx"),
  "./components/mockups/medigo/PatientHome.tsx": () => import("../components/mockups/medigo/PatientHome.tsx"),
  "./components/mockups/medigo/PatientRecords.tsx": () => import("../components/mockups/medigo/PatientRecords.tsx"),
  "./components/mockups/medigo/QueueDisplay.tsx": () => import("../components/mockups/medigo/QueueDisplay.tsx"),
  "./components/mockups/medigo/ReceptionPOS.tsx": () => import("../components/mockups/medigo/ReceptionPOS.tsx")
};
